# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LiveQ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LiveQ
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON', '~> 4.0'

end
