-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQBrLQ60S4TlWguRB
oXLRmYUL6pqxDt/gtfXHivxH0qCgCgYIKoZIzj0DAQehRANCAARYxJjvueLnqHqH
GbAtPsfp9pY6UWnAAEJhojEx6OtaKjSgxDRJdE6nXFsaCzLxf0NWk2wYVF/pvI9p
yTFWYi8K
-----END PRIVATE KEY-----