# Generated by Django 3.0.5 on 2020-04-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0002_auto_20200428_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
    ]
