# Generated by Django 3.0.5 on 2020-04-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0003_remove_room_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(default='XJyycb1h', max_length=8, primary_key=True, serialize=False),
        ),
    ]
