# Generated by Django 3.0.5 on 2020-04-28 09:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0005_auto_20200428_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AlterField(
            model_name='guest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(default='3vXzbyD9', max_length=8, primary_key=True, serialize=False),
        ),
    ]
