# Generated by Django 3.0.5 on 2020-04-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0007_auto_20200428_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(default='F7rEE3Q6', max_length=8, primary_key=True, serialize=False),
        ),
    ]
