# Generated by Django 3.0.5 on 2020-04-28 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0008_auto_20200428_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=8, unique=True),
        ),
    ]
