# Generated by Django 3.0.5 on 2020-04-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0012_auto_20200428_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveq.Room', to_field='room_key'),
        ),
    ]
