# Generated by Django 3.0.5 on 2020-04-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0013_auto_20200428_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='room',
        ),
        migrations.AlterField(
            model_name='song',
            name='image_uri',
            field=models.CharField(max_length=200),
        ),
    ]
