# Generated by Django 3.0.5 on 2020-04-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0014_auto_20200428_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('SPOT', 'Spotify'), ('SC', 'SoundCloud')], max_length=20),
        ),
    ]
