# Generated by Django 3.0.5 on 2020-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0015_auto_20200428_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='service',
            field=models.CharField(max_length=15),
        ),
    ]
