# Generated by Django 3.0.5 on 2020-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0016_auto_20200428_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_key',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
