# Generated by Django 3.0.5 on 2020-04-28 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0017_auto_20200428_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveq.Room', to_field='room_key'),
            preserve_default=False,
        ),
    ]
