# Generated by Django 3.0.5 on 2020-04-28 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0018_service_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(choices=[('Spotify', 'Spotify'), ('SoundCloud', 'SoundCloud')], max_length=20),
            preserve_default=False,
        ),
    ]
