# Generated by Django 3.0.5 on 2020-04-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveq', '0019_auto_20200428_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service',
            new_name='service_type',
        ),
    ]
