# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='interface.proto',
  package='liveq',
  syntax='proto3',
  serialized_options=b'\n\rio.grpc.LiveQB\nLiveQProtoP\001\242\002\002LQ',
  serialized_pb=b'\n\x0finterface.proto\x12\x05liveq\"\"\n\rCreateRequest\x12\x11\n\troom_name\x18\x01 \x01(\t\"0\n\x0b\x43reateReply\x12\x10\n\x08room_key\x18\x01 \x01(\t\x12\x0f\n\x07host_id\x18\x02 \x01(\t\"\x1f\n\x0bJoinRequest\x12\x10\n\x08room_key\x18\x01 \x01(\t\"\x1d\n\tJoinReply\x12\x10\n\x08guest_id\x18\x01 \x01(\t\" \n\x0cQueueRequest\x12\x10\n\x08room_key\x18\x01 \x01(\t\"1\n\nQueueReply\x12\x0f\n\x07song_id\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\t\"D\n\x0bSongRequest\x12\x0f\n\x07song_id\x18\x01 \x01(\t\x12\x12\n\nservice_id\x18\x02 \x01(\t\x12\x10\n\x08room_key\x18\x03 \x01(\t\"\x1b\n\tSongReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x99\x02\n\x05LiveQ\x12\x38\n\nCreateRoom\x12\x14.liveq.CreateRequest\x1a\x12.liveq.CreateReply\"\x00\x12\x32\n\x08JoinRoom\x12\x12.liveq.JoinRequest\x1a\x10.liveq.JoinReply\"\x00\x12\x39\n\x0bUpdateQueue\x12\x13.liveq.QueueRequest\x1a\x11.liveq.QueueReply\"\x00\x30\x01\x12\x31\n\x07\x41\x64\x64Song\x12\x12.liveq.SongRequest\x1a\x10.liveq.SongReply\"\x00\x12\x34\n\nDeleteSong\x12\x12.liveq.SongRequest\x1a\x10.liveq.SongReply\"\x00\x42\"\n\rio.grpc.LiveQB\nLiveQProtoP\x01\xa2\x02\x02LQb\x06proto3'
)




_CREATEREQUEST = _descriptor.Descriptor(
  name='CreateRequest',
  full_name='liveq.CreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_name', full_name='liveq.CreateRequest.room_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_CREATEREPLY = _descriptor.Descriptor(
  name='CreateReply',
  full_name='liveq.CreateReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_key', full_name='liveq.CreateReply.room_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='host_id', full_name='liveq.CreateReply.host_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=110,
)


_JOINREQUEST = _descriptor.Descriptor(
  name='JoinRequest',
  full_name='liveq.JoinRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_key', full_name='liveq.JoinRequest.room_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=143,
)


_JOINREPLY = _descriptor.Descriptor(
  name='JoinReply',
  full_name='liveq.JoinReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='guest_id', full_name='liveq.JoinReply.guest_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=174,
)


_QUEUEREQUEST = _descriptor.Descriptor(
  name='QueueRequest',
  full_name='liveq.QueueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='room_key', full_name='liveq.QueueRequest.room_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=208,
)


_QUEUEREPLY = _descriptor.Descriptor(
  name='QueueReply',
  full_name='liveq.QueueReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='song_id', full_name='liveq.QueueReply.song_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='liveq.QueueReply.service_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=259,
)


_SONGREQUEST = _descriptor.Descriptor(
  name='SongRequest',
  full_name='liveq.SongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='song_id', full_name='liveq.SongRequest.song_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_id', full_name='liveq.SongRequest.service_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_key', full_name='liveq.SongRequest.room_key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=329,
)


_SONGREPLY = _descriptor.Descriptor(
  name='SongReply',
  full_name='liveq.SongReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='liveq.SongReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=358,
)

DESCRIPTOR.message_types_by_name['CreateRequest'] = _CREATEREQUEST
DESCRIPTOR.message_types_by_name['CreateReply'] = _CREATEREPLY
DESCRIPTOR.message_types_by_name['JoinRequest'] = _JOINREQUEST
DESCRIPTOR.message_types_by_name['JoinReply'] = _JOINREPLY
DESCRIPTOR.message_types_by_name['QueueRequest'] = _QUEUEREQUEST
DESCRIPTOR.message_types_by_name['QueueReply'] = _QUEUEREPLY
DESCRIPTOR.message_types_by_name['SongRequest'] = _SONGREQUEST
DESCRIPTOR.message_types_by_name['SongReply'] = _SONGREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateRequest = _reflection.GeneratedProtocolMessageType('CreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.CreateRequest)
  })
_sym_db.RegisterMessage(CreateRequest)

CreateReply = _reflection.GeneratedProtocolMessageType('CreateReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.CreateReply)
  })
_sym_db.RegisterMessage(CreateReply)

JoinRequest = _reflection.GeneratedProtocolMessageType('JoinRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.JoinRequest)
  })
_sym_db.RegisterMessage(JoinRequest)

JoinReply = _reflection.GeneratedProtocolMessageType('JoinReply', (_message.Message,), {
  'DESCRIPTOR' : _JOINREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.JoinReply)
  })
_sym_db.RegisterMessage(JoinReply)

QueueRequest = _reflection.GeneratedProtocolMessageType('QueueRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.QueueRequest)
  })
_sym_db.RegisterMessage(QueueRequest)

QueueReply = _reflection.GeneratedProtocolMessageType('QueueReply', (_message.Message,), {
  'DESCRIPTOR' : _QUEUEREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.QueueReply)
  })
_sym_db.RegisterMessage(QueueReply)

SongRequest = _reflection.GeneratedProtocolMessageType('SongRequest', (_message.Message,), {
  'DESCRIPTOR' : _SONGREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.SongRequest)
  })
_sym_db.RegisterMessage(SongRequest)

SongReply = _reflection.GeneratedProtocolMessageType('SongReply', (_message.Message,), {
  'DESCRIPTOR' : _SONGREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:liveq.SongReply)
  })
_sym_db.RegisterMessage(SongReply)


DESCRIPTOR._options = None

_LIVEQ = _descriptor.ServiceDescriptor(
  name='LiveQ',
  full_name='liveq.LiveQ',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=361,
  serialized_end=642,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateRoom',
    full_name='liveq.LiveQ.CreateRoom',
    index=0,
    containing_service=None,
    input_type=_CREATEREQUEST,
    output_type=_CREATEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='JoinRoom',
    full_name='liveq.LiveQ.JoinRoom',
    index=1,
    containing_service=None,
    input_type=_JOINREQUEST,
    output_type=_JOINREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateQueue',
    full_name='liveq.LiveQ.UpdateQueue',
    index=2,
    containing_service=None,
    input_type=_QUEUEREQUEST,
    output_type=_QUEUEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddSong',
    full_name='liveq.LiveQ.AddSong',
    index=3,
    containing_service=None,
    input_type=_SONGREQUEST,
    output_type=_SONGREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteSong',
    full_name='liveq.LiveQ.DeleteSong',
    index=4,
    containing_service=None,
    input_type=_SONGREQUEST,
    output_type=_SONGREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIVEQ)

DESCRIPTOR.services_by_name['LiveQ'] = _LIVEQ

# @@protoc_insertion_point(module_scope)
